package com.rogerpf.aabridge.dds;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : line 256</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class allParResults extends Structure {
	/** C type : parResults[32] */
	public parResults[] presults = new parResults[32];

	public allParResults() {
		super();
	}

	protected List<?> getFieldOrder() {
		return Arrays.asList("presults");
	}

	/** @param presults C type : parResults[32] */
	public allParResults(parResults presults[]) {
		super();
		if ((presults.length != this.presults.length))
			throw new IllegalArgumentException("Wrong array size !");
		this.presults = presults;
	}

	public allParResults(Pointer peer) {
		super(peer);
	}

	public static class ByReference extends allParResults implements Structure.ByReference {

	};

	public static class ByValue extends allParResults implements Structure.ByValue {

	};
}
