package com.rogerpf.aabridge.dds;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : line 240</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ddTablesRes extends Structure {
	public int noOfBoards;
	/** C type : ddTableResults[32 * 5] */
	public ddTableResults[] results = new ddTableResults[32 * 5];

	public ddTablesRes() {
		super();
	}

	protected List<?> getFieldOrder() {
		return Arrays.asList("noOfBoards", "results");
	}

	/** @param results C type : ddTableResults[32 * 5] */
	public ddTablesRes(int noOfBoards, ddTableResults results[]) {
		super();
		this.noOfBoards = noOfBoards;
		if ((results.length != this.results.length))
			throw new IllegalArgumentException("Wrong array size !");
		this.results = results;
	}

	public ddTablesRes(Pointer peer) {
		super(peer);
	}

	public static class ByReference extends ddTablesRes implements Structure.ByReference {

	};

	public static class ByValue extends ddTablesRes implements Structure.ByValue {

	};
}
