package com.rogerpf.aabridge.dds;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : line 218</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ddTableDeals extends Structure {
	public int noOfTables;
	/** C type : ddTableDeal[32 * 5] */
	public ddTableDeal[] deals = new ddTableDeal[32 * 5];

	public ddTableDeals() {
		super();
	}

	protected List<?> getFieldOrder() {
		return Arrays.asList("noOfTables", "deals");
	}

	/** @param deals C type : ddTableDeal[32 * 5] */
	public ddTableDeals(int noOfTables, ddTableDeal deals[]) {
		super();
		this.noOfTables = noOfTables;
		if ((deals.length != this.deals.length))
			throw new IllegalArgumentException("Wrong array size !");
		this.deals = deals;
	}

	public ddTableDeals(Pointer peer) {
		super(peer);
	}

	public static class ByReference extends ddTableDeals implements Structure.ByReference {

	};

	public static class ByValue extends ddTableDeals implements Structure.ByValue {

	};
}
