package com.rogerpf.aabridge.dds;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : line 261</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class parResultsDealer extends Structure {
	public int number;
	public int score;
	/** C type : char[10][10] */
	public byte[] contracts = new byte[((10) * (10))];

	public parResultsDealer() {
		super();
	}

	protected List<?> getFieldOrder() {
		return Arrays.asList("number", "score", "contracts");
	}

	/** @param contracts C type : char[10][10] */
	public parResultsDealer(int number, int score, byte contracts[]) {
		super();
		this.number = number;
		this.score = score;
		if ((contracts.length != this.contracts.length))
			throw new IllegalArgumentException("Wrong array size !");
		this.contracts = contracts;
	}

	public parResultsDealer(Pointer peer) {
		super(peer);
	}

	public static class ByReference extends parResultsDealer implements Structure.ByReference {

	};

	public static class ByValue extends parResultsDealer implements Structure.ByValue {

	};
}
