package com.rogerpf.aabridge.dds;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : line 302</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class playTracePBN extends Structure {
	public int number;
	/** C type : char[106] */
	public byte[] cards = new byte[106];

	public playTracePBN() {
		super();
	}

	protected List<?> getFieldOrder() {
		return Arrays.asList("number", "cards");
	}

	/** @param cards C type : char[106] */
	public playTracePBN(int number, byte cards[]) {
		super();
		this.number = number;
		if ((cards.length != this.cards.length))
			throw new IllegalArgumentException("Wrong array size !");
		this.cards = cards;
	}

	public playTracePBN(Pointer peer) {
		super(peer);
	}

	public static class ByReference extends playTracePBN implements Structure.ByReference {

	};

	public static class ByValue extends playTracePBN implements Structure.ByValue {

	};
}
