package com.rogerpf.aabridge.dds;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : line 314</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class playTracesBin extends Structure {
	public int noOfBoards;
	/** C type : playTraceBin[200] */
	public playTraceBin[] plays = new playTraceBin[200];

	public playTracesBin() {
		super();
	}

	protected List<?> getFieldOrder() {
		return Arrays.asList("noOfBoards", "plays");
	}

	/** @param plays C type : playTraceBin[200] */
	public playTracesBin(int noOfBoards, playTraceBin plays[]) {
		super();
		this.noOfBoards = noOfBoards;
		if ((plays.length != this.plays.length))
			throw new IllegalArgumentException("Wrong array size !");
		this.plays = plays;
	}

	public playTracesBin(Pointer peer) {
		super(peer);
	}

	public static class ByReference extends playTracesBin implements Structure.ByReference {

	};

	public static class ByValue extends playTracesBin implements Structure.ByValue {

	};
}
