package com.rogerpf.aabridge.dds;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : line 308</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class solvedPlay extends Structure {
	public int number;
	/** C type : int[53] */
	public int[] tricks = new int[53];

	public solvedPlay() {
		super();
	}

	protected List<?> getFieldOrder() {
		return Arrays.asList("number", "tricks");
	}

	/** @param tricks C type : int[53] */
	public solvedPlay(int number, int tricks[]) {
		super();
		this.number = number;
		if ((tricks.length != this.tricks.length))
			throw new IllegalArgumentException("Wrong array size !");
		this.tricks = tricks;
	}

	public solvedPlay(Pointer peer) {
		super(peer);
	}

	public static class ByReference extends solvedPlay implements Structure.ByReference {

	};

	public static class ByValue extends solvedPlay implements Structure.ByValue {

	};
}
