@echo\
@echo  You may want to edit this  .cmd  file to read the notes inside it.
@echo\

@echo off


rem    
rem     This launches the latest (alphabetically last) version of aaBridge
rem       in windows 'cmd' box.  
rem     Doing this lets you see any messages generated by aaBridge as you use it.
rem       such as:-   
rem                  Line xxx  pg nn  Card played not in hand! ...
rem    
rem     If you see a message saying ..
rem    
rem      WARNING: Could not open/create prefs root node Software JavaSoft Prefs ...
rem    
rem     you can ignore it.  TO HAVE IT GO AWAY, run this .cmd from the mouse right
rem     button menu and select  "Run as administrator"     ONLY NEEDED ONCE
rem    
rem    
rem     High res systems which have done the  "Java too small fonts fix"  
rem      see   "aaBridge on YouTuble"  -  Overly Small System Fonts and aaBridge
rem      will need to Java differently (to get their normal sized fonts).
rem      Edit this file and set your Java location to whatever Java you did 
rem      the font fix on.  
rem        IE   Enable and/or edit one of the  "location"  lines that follow.
rem         (to enable one of the lines - edit it to remove the "REM" see below)
rem    
 

cd C:\ProgramSmall\aaBridge

REM  set java_location="C:\Program Files (x86)\Java\jre6\bin\"
REM  set java_location="C:\Program Files (x86)\Java\jre7\bin\"
REM  set java_location="C:\Program Files (x86)\Java\jdk1.7.0_79\bin\"
REM  set java_location="C:\Program Files (x86)\Java\jre1.8.0_121\bin\"
REM  set java_location="C:\Program Files (x86)\Java\jre1.8.0_181\bin\"
REM  set java_location="C:\Program Files\Java\jre1.8.0_161\bin\"
REM  set java_location="C:\Program Files\Java\jre1.8.0_181\bin\"
REM  set java_location="C:\Program Files\Java\jre-10.0.2\bin\"

FOR /F "delims=|" %%I IN ('DIR "aaBridge_*.jar" /B /O:N') DO SET highestVersion=%%I

@echo on

%java_location%java.exe   -jar   %highestVersion%

@echo\
@pause
